<?php

namespace PictureChat\FileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
    /**
     * 
     */
    public function filesChangedBy ( $id) {
        
        return $this->createQueryBuilder('f')
                    ->where("f.id > :id")
                    ->setParameter('id', $id)
                    ->addOrderBy('f.id', 'DESC')
                ->getQuery()
                ->getResult()
                ;                        
    }
}
